version: '3.8'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.10.0
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false        # Disable security features (authentication, HTTPS)
      - xpack.security.http.ssl.enabled=false # Disable HTTPS
    ports:
      - "9200:9200"
      - "9300:9300"

  # go-api:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   container_name: go-api
  #   environment:
  #     - ELASTICSEARCH_HOST=http://elasticsearch:9200
  #   ports:
  #     - "8080:8080"
  #   depends_on:
  #     - elasticsearch
  #   volumes:
  #     - ./app:/app
  #   working_dir: /app
  #   deploy:
  #     resources:
  #       limits:
  #         memory: 1g # Limit memory usage
  #         cpus: "0.5" # Allocate 0.5 CPU core to API
  #     restart_policy:
  #       condition: on-failure