name: Build, Push, and Deploy Docker Image

on:
  workflow_call:
    inputs:
        version:
          default: "latest"
          type: string

jobs:
  deploy:
    name: Deploy Docker Image
    runs-on: ubuntu-latest
    steps:
      - name: Docker login
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ vars.VM_HOST }}
          username: ${{ vars.VM_USERNAME }}
          key: ${{ secrets.VM_SSH_PRIVATE_KEY }}
          proxy_host: ${{ vars.DEPLOYMENT_GATEWAY_HOST }}
          proxy_username: ${{ vars.DEPLOYMENT_GATEWAY_USER }}
          proxy_key: ${{ secrets.VM_SSH_PRIVATE_KEY }}
          script: |
            export CR_PAT=${{ secrets.PULL_ACCESS_TOKEN }}
            echo $CR_PAT | docker login ghcr.io -u USERNAME --password-stdin

      - name: Stop docker containers
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ vars.VM_HOST }}
          username: ${{ vars.VM_USERNAME }}
          key: ${{ secrets.VM_SSH_PRIVATE_KEY }}
          proxy_host: ${{ vars.DEPLOYMENT_GATEWAY_HOST }}
          proxy_username: ${{ vars.DEPLOYMENT_GATEWAY_USER }}
          proxy_key: ${{ secrets.VM_SSH_PRIVATE_KEY }}
          script: |
            docker compose down 

      - name: create env file
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ vars.VM_HOST }}
          username: ${{ vars.VM_USERNAME }}
          key: ${{ secrets.VM_SSH_PRIVATE_KEY }}
          proxy_host: ${{ vars.DEPLOYMENT_GATEWAY_HOST }}
          proxy_username: ${{ vars.DEPLOYMENT_GATEWAY_USER }}
          proxy_key: ${{ secrets.VM_SSH_PRIVATE_KEY }}
          script: |
            echo "TAG=${{ inputs.version }}" > ~/.env
            docker compose pull 

      - name: Copy docker compose file to host 
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ vars.VM_HOST }}
          username: ${{ vars.VM_USERNAME }}
          key: ${{ secrets.VM_SSH_PRIVATE_KEY }}
          proxy_host: ${{ vars.DEPLOYMENT_GATEWAY_HOST }}
          proxy_username: ${{ vars.DEPLOYMENT_GATEWAY_USER }}
          proxy_key: ${{ secrets.VM_SSH_PRIVATE_KEY }}
          source: docker-compose.yml
          target: ~/docker-compose.yml
