name: Build Image

on:
  push:
    branches: [main]

jobs:
  build-container:
    uses: ./.github/workflows/build-image.yml
    secrets: inherit
  deploy-dev-container:
    needs: build-container
    uses: ./.github/workflows/deploy-image.yml
    secrets: inherit
    with:
      version: "${{ needs.build-container.outputs.version }}"